# Generated by Django 5.0.3 on 2024-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lanzamientos/'),
        ),
        migrations.AlterField(
            model_name='tipolanzamiento',
            name='nombreTipo',
            field=models.CharField(max_length=20),
        ),
    ]
