# Generated by Django 5.0.6 on 2024-05-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artista_imagen_lanzamiento_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('lanzamiento', 'Lanzamiento'), ('artista', 'Artista'), ('genero', 'Género Musical')], max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('detalles', models.TextField()),
            ],
            options={
                'verbose_name': 'Solicitud de Aprobación',
                'verbose_name_plural': 'Solicitudes de Aprobación',
            },
        ),
        # Este cambio se realiza para modificar el campo 'imagen' en el modelo 'Artista'.
        # Se especifica el directorio 'artistas/' donde se subirán las imágenes de los artistas.
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(upload_to='artistas/'),
        ),
    ]
