# Generated by Django 5.0.6 on 2024-05-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudaprobacion_alter_artista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaprobacion',
            name='aprobado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
