# Generated by Django 5.0.6 on 2024-05-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitudaprobacion_aprobado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudAprobacion',
        ),
        migrations.AddField(
            model_name='artista',
            name='aprobado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='generomusical',
            name='aprobado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='aprobado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
