# Generated by Django 5.0.6 on 2024-05-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_solicitudaprobacion_artista_aprobado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generomusical',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
