# Generated by Django 5.0.6 on 2024-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artista_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipolanzamiento',
            name='aprobado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tipolanzamiento',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
