# Generated by Django 5.0.6 on 2024-05-27 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipolanzamiento_aprobado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='fecha_solicitud',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='generomusical',
            name='fecha_solicitud',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='lanzamiento',
            name='fecha_solicitud',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='tipolanzamiento',
            name='fecha_solicitud',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
