# Generated by Django 5.0.6 on 2024-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_artista_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
