# Generated by Django 5.0.6 on 2024-05-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_artista_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='generomusical',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tipolanzamiento',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
