# Generated by Django 5.0.3 on 2024-06-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carritohistorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoHistorial',
        ),
    ]
