# Generated by Django 5.0.6 on 2024-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historialpagosusuario_delete_historial_pagos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpagosusuario',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
