# Generated by Django 5.0.6 on 2024-06-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_carritohistorial'),
        ('core', '0014_alter_historialpagosusuario_metodo_pago'),
    ]

    operations = [
    ]
